### PR TITLE
ci: Disable presubmit LLM tests temporarily

### PR DESCRIPTION
**Pull request by shobsi**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-dataframes/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by milkshakeiii — APPROVED** [review]
LGTM although is LLM capacity the only ML capacity we ran up against?

**Comment by milkshakeiii** [comment]
> LGTM although is LLM capacity the only ML capacity we ran up against?

I guess merging this will help answer that question!

**Comment by shobsi** [comment]
> > LGTM although is LLM capacity the only ML capacity we ran up against?
> 
> I guess merging this will help answer that question!

Yeah, we were wondering about the slot reservation but it seems we are well within the capacity https://screenshot.googleplex.com/5VDoK8TXXsrLUtH

**Review by ashleyxuu — APPROVED** [review]
LGTM. I'll dig deeper into these test when I get time.

**Comment by shobsi** [comment]
The presubmit test still took 1h17m

https://fusion2.corp.google.com/ci/kokoro/prod:bigframes%2Fpresubmit%2Fpresubmit/activity/d238d224-d057-4545-9500-11b99fefde5d/summary

I am reverting this change in https://github.com/googleapis/python-bigquery-dataframes/pull/148

**Pull request merged**
