### PR TITLE
docs: add streaming html docs

### PR DESCRIPTION
**Pull request by GarrettWu**
Verified locally.

### CODE REVIEW

**Review by jiaxunwu — APPROVED** [review]
for streaming.dataframe, could you add notes about what is supported there? for example, you can simply list the operations allowed at this moment.

**Review by chelsea-lin — APPROVED** [review]

**Review by chelsea-lin — APPROVED** [review]
Can you please link the staging doc with this change in the PR descriptions, if you have

**Comment by GarrettWu** [comment]
> Can you please link the staging doc with this change in the PR descriptions, if you have

https://cloud.devsite.corp.google.com/python/docs/reference/bigframes/latest

**Comment by GarrettWu** [comment]
> for streaming.dataframe, could you add notes about what is supported there? for example, you can simply list the operations allowed at this moment.

done

**Pull request merged**
