### PR TITLE
test: allow more retries on claude tests

### PR DESCRIPTION
**Pull request by shobsi**
This should accommodate more flakiness in the not-so-stable claude endpoints.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-dataframes/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by tswast — APPROVED** [review]
I wonder if these are incorrectly classified as "small"? The flakiness on presubmits is very concerning to me.

**Comment by tswast** [comment]
I'm using admin permissions to merge this as well, as the claude tests are indeed passing and the encryption failure is unrelated.

**Comment by shobsi** [comment]
> I wonder if these are incorrectly classified as "small"? The flakiness on presubmits is very concerning to me.

@GarrettWu how do we think of the LLM integration tests being under small tests. IIRC there have been instabilities in the other LLM tests (Palm2, Gemini) as well. Should we move them under e2e tests?

**Comment by GarrettWu** [comment]
> > I wonder if these are incorrectly classified as "small"? The flakiness on presubmits is very concerning to me.
> 
> @GarrettWu how do we think of the LLM integration tests being under small tests. IIRC there have been instabilities in the other LLM tests (Palm2, Gemini) as well. Should we move them under e2e tests?

They are considered small since they are just small and short tests. Usually we put training tests to large.
There are 2 different issues with this:
1. load failed for 500: this one is new and it is a real issue instead of flakiness. I'd bring this up in today's meeting with BQML.
2. flakiness on the content: we have some updates that don't check the contents. While some tests are missed for that change. I'd send a PR to update.

**Pull request merged**
